// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {monitor} from '../models';
import {vm} from '../models';

export function BridgeList(arg1:string):Promise<Array<string>>;

export function CreateVolume(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<string>;

export function HostAdd(arg1:store.Host):Promise<void>;

export function HostConnect(arg1:string):Promise<void>;

export function HostDelete(arg1:string):Promise<void>;

export function HostDisconnect(arg1:string):Promise<void>;

export function HostExportJSON():Promise<string>;

export function HostImportJSON(arg1:string):Promise<number>;

export function HostIsConnected(arg1:string):Promise<boolean>;

export function HostList():Promise<Array<store.Host>>;

export function HostResourceStats(arg1:string):Promise<monitor.HostStats>;

export function HostTest(arg1:store.Host):Promise<void>;

export function HostUpdate(arg1:store.Host):Promise<void>;

export function ISOList(arg1:string):Promise<Array<vm.ISOFile>>;

export function NetworkList(arg1:string):Promise<Array<vm.Network>>;

export function OSVariantList(arg1:string):Promise<Array<string>>;

export function PoolList(arg1:string):Promise<Array<vm.StoragePool>>;

export function SettingGet(arg1:string):Promise<string>;

export function SettingSet(arg1:string,arg2:string):Promise<void>;

export function SnapshotCreate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SnapshotDelete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SnapshotList(arg1:string,arg2:string):Promise<Array<vm.Snapshot>>;

export function SnapshotRevert(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TerminalPort():Promise<number>;

export function VMAttachDisk(arg1:string,arg2:string,arg3:vm.DiskAttachParams):Promise<void>;

export function VMAttachInterface(arg1:string,arg2:string,arg3:vm.NICAttachParams):Promise<void>;

export function VMChangeMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function VMClone(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMCreate(arg1:string,arg2:vm.VMCreateParams):Promise<void>;

export function VMDefineXML(arg1:string,arg2:string):Promise<void>;

export function VMDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMDestroy(arg1:string,arg2:string):Promise<void>;

export function VMDetachDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMDetachInterface(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMEjectMedia(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMGet(arg1:string,arg2:string):Promise<vm.VMDetail>;

export function VMGetXML(arg1:string,arg2:string):Promise<string>;

export function VMList(arg1:string):Promise<Array<vm.VM>>;

export function VMReboot(arg1:string,arg2:string):Promise<void>;

export function VMRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMResizeDisk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMResume(arg1:string,arg2:string):Promise<void>;

export function VMSetAutostart(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMSetGraphics(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMSetMemory(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMSetVCPUs(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMShutdown(arg1:string,arg2:string):Promise<void>;

export function VMStart(arg1:string,arg2:string):Promise<void>;

export function VMStats(arg1:string,arg2:string):Promise<vm.VMResourceStats>;

export function VMSuspend(arg1:string,arg2:string):Promise<void>;

export function VolList(arg1:string,arg2:string):Promise<Array<vm.Volume>>;
