// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {monitor} from '../models';
import {vm} from '../models';

export function AppVersion():Promise<string>;

export function AuditList(arg1:string,arg2:number):Promise<Array<store.AuditRecord>>;

export function AuditListAll(arg1:number):Promise<Array<store.AuditRecord>>;

export function BridgeList(arg1:string):Promise<Array<string>>;

export function CreateVolume(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<string>;

export function DeleteVolume(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FlavorAdd(arg1:store.Flavor):Promise<void>;

export function FlavorDelete(arg1:string):Promise<void>;

export function FlavorList():Promise<Array<store.Flavor>>;

export function FlavorUpdate(arg1:store.Flavor):Promise<void>;

export function HostAdd(arg1:store.Host):Promise<void>;

export function HostCheckTools(arg1:string):Promise<Record<string, string>>;

export function HostConnect(arg1:string):Promise<void>;

export function HostDelete(arg1:string):Promise<void>;

export function HostDetectDistro(arg1:string):Promise<string>;

export function HostDisconnect(arg1:string):Promise<void>;

export function HostExportJSON():Promise<string>;

export function HostGetFingerprint(arg1:string):Promise<string>;

export function HostImageDelete(arg1:string,arg2:string):Promise<void>;

export function HostImageScan(arg1:string):Promise<Array<main.HostImageFile>>;

export function HostImportJSON(arg1:string):Promise<number>;

export function HostIsConnected(arg1:string):Promise<boolean>;

export function HostList():Promise<Array<store.Host>>;

export function HostResetHostKey(arg1:string):Promise<void>;

export function HostResourceStats(arg1:string):Promise<monitor.HostStats>;

export function HostRunScript(arg1:string,arg2:string):Promise<string>;

export function HostStatsHistory(arg1:string,arg2:number):Promise<Array<store.HostStatsRecord>>;

export function HostTest(arg1:store.Host):Promise<string>;

export function HostUpdate(arg1:store.Host):Promise<void>;

export function ISOList(arg1:string):Promise<Array<vm.ISOFile>>;

export function ImageAdd(arg1:string,arg2:store.Image):Promise<void>;

export function ImageDelete(arg1:string):Promise<void>;

export function ImageImport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ImageImportStatus():Promise<Array<main.importTask>>;

export function ImageList(arg1:string):Promise<Array<store.Image>>;

export function ImageSourceAdd(arg1:store.ImageSource):Promise<void>;

export function ImageSourceDelete(arg1:string):Promise<void>;

export function ImageSourceList():Promise<Array<store.ImageSource>>;

export function ImageSourceUpdate(arg1:store.ImageSource):Promise<void>;

export function ImageUpdate(arg1:store.Image):Promise<void>;

export function ImageUpload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function InstanceByVMName(arg1:string,arg2:string):Promise<store.Instance>;

export function InstanceISOList(arg1:string,arg2:number):Promise<Array<vm.ISOFile>>;

export function InstanceList(arg1:string):Promise<Array<store.Instance>>;

export function LibvirtSetupScriptList():Promise<Array<main.LibvirtSetupScript>>;

export function NATRuleAdd(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function NATRuleDelete(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function NATRuleList(arg1:string):Promise<Array<vm.NATRule>>;

export function NetworkAutostart(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function NetworkList(arg1:string):Promise<Array<vm.Network>>;

export function NetworkStart(arg1:string,arg2:string):Promise<void>;

export function NetworkStop(arg1:string,arg2:string):Promise<void>;

export function OSVariantList(arg1:string):Promise<Array<string>>;

export function PoolAutostart(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function PoolList(arg1:string):Promise<Array<vm.StoragePool>>;

export function PoolStart(arg1:string,arg2:string):Promise<void>;

export function PoolStop(arg1:string,arg2:string):Promise<void>;

export function SettingGet(arg1:string):Promise<string>;

export function SettingSet(arg1:string,arg2:string):Promise<void>;

export function SnapshotCreate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SnapshotDelete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SnapshotList(arg1:string,arg2:string):Promise<Array<vm.Snapshot>>;

export function SnapshotRevert(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TerminalPort():Promise<number>;

export function VMAttachDisk(arg1:string,arg2:string,arg3:vm.DiskAttachParams):Promise<void>;

export function VMAttachInterface(arg1:string,arg2:string,arg3:vm.NICAttachParams):Promise<void>;

export function VMChangeMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function VMClone(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMCreate(arg1:string,arg2:vm.VMCreateParams):Promise<void>;

export function VMCreateFromTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function VMDefineXML(arg1:string,arg2:string):Promise<void>;

export function VMDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMDestroy(arg1:string,arg2:string):Promise<void>;

export function VMDetachDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMDetachInterface(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMEjectMedia(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMGenerateCloudInit(arg1:string,arg2:string,arg3:vm.CloudInitConfig):Promise<void>;

export function VMGet(arg1:string,arg2:string):Promise<vm.VMDetail>;

export function VMGetXML(arg1:string,arg2:string):Promise<string>;

export function VMList(arg1:string):Promise<Array<vm.VM>>;

export function VMMigrate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMMigrateOffline(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMNoteGet(arg1:string,arg2:string):Promise<string>;

export function VMNoteSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMReboot(arg1:string,arg2:string):Promise<void>;

export function VMRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VMResizeDisk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMResume(arg1:string,arg2:string):Promise<void>;

export function VMSetAutostart(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMSetGraphics(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VMSetMemory(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMSetVCPUs(arg1:string,arg2:string,arg3:number):Promise<void>;

export function VMShutdown(arg1:string,arg2:string):Promise<void>;

export function VMStart(arg1:string,arg2:string):Promise<void>;

export function VMStats(arg1:string,arg2:string):Promise<vm.VMResourceStats>;

export function VMStatsHistory(arg1:string,arg2:string,arg3:number):Promise<Array<store.VMStatsRecord>>;

export function VMSuspend(arg1:string,arg2:string):Promise<void>;

export function VolList(arg1:string,arg2:string):Promise<Array<vm.Volume>>;
