// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AuditList(arg1, arg2) {
  return window['go']['main']['App']['AuditList'](arg1, arg2);
}

export function AuditListAll(arg1) {
  return window['go']['main']['App']['AuditListAll'](arg1);
}

export function BridgeList(arg1) {
  return window['go']['main']['App']['BridgeList'](arg1);
}

export function CreateVolume(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateVolume'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteVolume'](arg1, arg2, arg3);
}

export function FlavorAdd(arg1) {
  return window['go']['main']['App']['FlavorAdd'](arg1);
}

export function FlavorDelete(arg1) {
  return window['go']['main']['App']['FlavorDelete'](arg1);
}

export function FlavorList() {
  return window['go']['main']['App']['FlavorList']();
}

export function FlavorUpdate(arg1) {
  return window['go']['main']['App']['FlavorUpdate'](arg1);
}

export function HostAdd(arg1) {
  return window['go']['main']['App']['HostAdd'](arg1);
}

export function HostCheckTools(arg1) {
  return window['go']['main']['App']['HostCheckTools'](arg1);
}

export function HostConnect(arg1) {
  return window['go']['main']['App']['HostConnect'](arg1);
}

export function HostDelete(arg1) {
  return window['go']['main']['App']['HostDelete'](arg1);
}

export function HostDetectDistro(arg1) {
  return window['go']['main']['App']['HostDetectDistro'](arg1);
}

export function HostDisconnect(arg1) {
  return window['go']['main']['App']['HostDisconnect'](arg1);
}

export function HostExportJSON() {
  return window['go']['main']['App']['HostExportJSON']();
}

export function HostGetFingerprint(arg1) {
  return window['go']['main']['App']['HostGetFingerprint'](arg1);
}

export function HostImageDelete(arg1, arg2) {
  return window['go']['main']['App']['HostImageDelete'](arg1, arg2);
}

export function HostImageScan(arg1) {
  return window['go']['main']['App']['HostImageScan'](arg1);
}

export function HostImportJSON(arg1) {
  return window['go']['main']['App']['HostImportJSON'](arg1);
}

export function HostIsConnected(arg1) {
  return window['go']['main']['App']['HostIsConnected'](arg1);
}

export function HostList() {
  return window['go']['main']['App']['HostList']();
}

export function HostResetHostKey(arg1) {
  return window['go']['main']['App']['HostResetHostKey'](arg1);
}

export function HostResourceStats(arg1) {
  return window['go']['main']['App']['HostResourceStats'](arg1);
}

export function HostRunScript(arg1, arg2) {
  return window['go']['main']['App']['HostRunScript'](arg1, arg2);
}

export function HostStatsHistory(arg1, arg2) {
  return window['go']['main']['App']['HostStatsHistory'](arg1, arg2);
}

export function HostTest(arg1) {
  return window['go']['main']['App']['HostTest'](arg1);
}

export function HostUpdate(arg1) {
  return window['go']['main']['App']['HostUpdate'](arg1);
}

export function ISOList(arg1) {
  return window['go']['main']['App']['ISOList'](arg1);
}

export function ImageAdd(arg1, arg2) {
  return window['go']['main']['App']['ImageAdd'](arg1, arg2);
}

export function ImageDelete(arg1) {
  return window['go']['main']['App']['ImageDelete'](arg1);
}

export function ImageImport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImageImport'](arg1, arg2, arg3, arg4, arg5);
}

export function ImageImportStatus() {
  return window['go']['main']['App']['ImageImportStatus']();
}

export function ImageList(arg1) {
  return window['go']['main']['App']['ImageList'](arg1);
}

export function ImageSourceAdd(arg1) {
  return window['go']['main']['App']['ImageSourceAdd'](arg1);
}

export function ImageSourceDelete(arg1) {
  return window['go']['main']['App']['ImageSourceDelete'](arg1);
}

export function ImageSourceList() {
  return window['go']['main']['App']['ImageSourceList']();
}

export function ImageSourceUpdate(arg1) {
  return window['go']['main']['App']['ImageSourceUpdate'](arg1);
}

export function ImageUpdate(arg1) {
  return window['go']['main']['App']['ImageUpdate'](arg1);
}

export function ImageUpload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImageUpload'](arg1, arg2, arg3, arg4, arg5);
}

export function InitForServe() {
  return window['go']['main']['App']['InitForServe']();
}

export function InstanceByVMName(arg1, arg2) {
  return window['go']['main']['App']['InstanceByVMName'](arg1, arg2);
}

export function InstanceISOList(arg1, arg2) {
  return window['go']['main']['App']['InstanceISOList'](arg1, arg2);
}

export function InstanceList(arg1) {
  return window['go']['main']['App']['InstanceList'](arg1);
}

export function LibvirtSetupScriptList() {
  return window['go']['main']['App']['LibvirtSetupScriptList']();
}

export function NATRuleAdd(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['NATRuleAdd'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function NATRuleDelete(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['NATRuleDelete'](arg1, arg2, arg3, arg4, arg5);
}

export function NATRuleList(arg1) {
  return window['go']['main']['App']['NATRuleList'](arg1);
}

export function NetworkAutostart(arg1, arg2, arg3) {
  return window['go']['main']['App']['NetworkAutostart'](arg1, arg2, arg3);
}

export function NetworkList(arg1) {
  return window['go']['main']['App']['NetworkList'](arg1);
}

export function NetworkStart(arg1, arg2) {
  return window['go']['main']['App']['NetworkStart'](arg1, arg2);
}

export function NetworkStop(arg1, arg2) {
  return window['go']['main']['App']['NetworkStop'](arg1, arg2);
}

export function OSVariantList(arg1) {
  return window['go']['main']['App']['OSVariantList'](arg1);
}

export function PoolAutostart(arg1, arg2, arg3) {
  return window['go']['main']['App']['PoolAutostart'](arg1, arg2, arg3);
}

export function PoolList(arg1) {
  return window['go']['main']['App']['PoolList'](arg1);
}

export function PoolStart(arg1, arg2) {
  return window['go']['main']['App']['PoolStart'](arg1, arg2);
}

export function PoolStop(arg1, arg2) {
  return window['go']['main']['App']['PoolStop'](arg1, arg2);
}

export function SettingGet(arg1) {
  return window['go']['main']['App']['SettingGet'](arg1);
}

export function SettingSet(arg1, arg2) {
  return window['go']['main']['App']['SettingSet'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function SnapshotCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SnapshotCreate'](arg1, arg2, arg3);
}

export function SnapshotDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['SnapshotDelete'](arg1, arg2, arg3);
}

export function SnapshotList(arg1, arg2) {
  return window['go']['main']['App']['SnapshotList'](arg1, arg2);
}

export function SnapshotRevert(arg1, arg2, arg3) {
  return window['go']['main']['App']['SnapshotRevert'](arg1, arg2, arg3);
}

export function TerminalPort() {
  return window['go']['main']['App']['TerminalPort']();
}

export function VMAttachDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMAttachDisk'](arg1, arg2, arg3);
}

export function VMAttachInterface(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMAttachInterface'](arg1, arg2, arg3);
}

export function VMChangeMedia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VMChangeMedia'](arg1, arg2, arg3, arg4);
}

export function VMClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMClone'](arg1, arg2, arg3);
}

export function VMCreate(arg1, arg2) {
  return window['go']['main']['App']['VMCreate'](arg1, arg2);
}

export function VMCreateFromTemplate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['VMCreateFromTemplate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function VMDefineXML(arg1, arg2) {
  return window['go']['main']['App']['VMDefineXML'](arg1, arg2);
}

export function VMDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMDelete'](arg1, arg2, arg3);
}

export function VMDestroy(arg1, arg2) {
  return window['go']['main']['App']['VMDestroy'](arg1, arg2);
}

export function VMDetachDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMDetachDisk'](arg1, arg2, arg3);
}

export function VMDetachInterface(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMDetachInterface'](arg1, arg2, arg3);
}

export function VMEjectMedia(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMEjectMedia'](arg1, arg2, arg3);
}

export function VMGenerateCloudInit(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMGenerateCloudInit'](arg1, arg2, arg3);
}

export function VMGet(arg1, arg2) {
  return window['go']['main']['App']['VMGet'](arg1, arg2);
}

export function VMGetXML(arg1, arg2) {
  return window['go']['main']['App']['VMGetXML'](arg1, arg2);
}

export function VMList(arg1) {
  return window['go']['main']['App']['VMList'](arg1);
}

export function VMMigrate(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMMigrate'](arg1, arg2, arg3);
}

export function VMMigrateOffline(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMMigrateOffline'](arg1, arg2, arg3);
}

export function VMNoteGet(arg1, arg2) {
  return window['go']['main']['App']['VMNoteGet'](arg1, arg2);
}

export function VMNoteSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMNoteSet'](arg1, arg2, arg3);
}

export function VMReboot(arg1, arg2) {
  return window['go']['main']['App']['VMReboot'](arg1, arg2);
}

export function VMRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMRename'](arg1, arg2, arg3);
}

export function VMResizeDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMResizeDisk'](arg1, arg2, arg3);
}

export function VMResume(arg1, arg2) {
  return window['go']['main']['App']['VMResume'](arg1, arg2);
}

export function VMSetAutostart(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMSetAutostart'](arg1, arg2, arg3);
}

export function VMSetGraphics(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMSetGraphics'](arg1, arg2, arg3);
}

export function VMSetMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMSetMemory'](arg1, arg2, arg3);
}

export function VMSetVCPUs(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMSetVCPUs'](arg1, arg2, arg3);
}

export function VMShutdown(arg1, arg2) {
  return window['go']['main']['App']['VMShutdown'](arg1, arg2);
}

export function VMStart(arg1, arg2) {
  return window['go']['main']['App']['VMStart'](arg1, arg2);
}

export function VMStats(arg1, arg2) {
  return window['go']['main']['App']['VMStats'](arg1, arg2);
}

export function VMStatsHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['VMStatsHistory'](arg1, arg2, arg3);
}

export function VMSuspend(arg1, arg2) {
  return window['go']['main']['App']['VMSuspend'](arg1, arg2);
}

export function VolList(arg1, arg2) {
  return window['go']['main']['App']['VolList'](arg1, arg2);
}
